name: Ingest RIVM COVID19 data

on:
  workflow_dispatch:
  schedule:
  - cron: '00 14 * * *'

jobs:
  ingest-rivm-covid19-data:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
#        working-directory: /
    env:
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_TENANT: ${{ secrets.APP_TENANT }}
      KUSTO_URL: ${{ secrets.KUSTO_URL }}
      INGESTION_URL: ${{ secrets.INGESTION_URL }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: "Install required packages"
      run: |
        pip3 install -r requirements.txt
    - name: "Run download_and_ingest_files.py"
      run: |
        python3 download_and_ingest_files.py
